// <auto-generated />
namespace SunLine.Community.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddCoverPatternName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCoverPatternName));
        
        string IMigrationMetadata.Id
        {
            get { return "201412290815281_AddCoverPatternName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
