//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunLine.Community.Resources.Titles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunLine.Community.Resources.Titles.UsersMessage", typeof(UsersMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories was saved successfully..
        /// </summary>
        public static string CategoriesSavedSuccessfully {
            get {
                return ResourceManager.GetString("CategoriesSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are starting to observe the user..
        /// </summary>
        public static string ConnectionWasCreated {
            get {
                return ResourceManager.GetString("ConnectionWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve stopped observing the user..
        /// </summary>
        public static string ConnectionWasRemoved {
            get {
                return ResourceManager.GetString("ConnectionWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover was saved successfully..
        /// </summary>
        public static string CoverSavedSuccessfully {
            get {
                return ResourceManager.GetString("CoverSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An error occurred while changing connection. Please try again..
        /// </summary>
        public static string ErrorWhileChangingConnection {
            get {
                return ResourceManager.GetString("ErrorWhileChangingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An error occurred while saving categories. Please try again..
        /// </summary>
        public static string ErrorWhileSavingCategories {
            get {
                return ResourceManager.GetString("ErrorWhileSavingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An error occurred while saving cover. Please try again..
        /// </summary>
        public static string ErrorWhileSavingCover {
            get {
                return ResourceManager.GetString("ErrorWhileSavingCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An error occurred while saving profile. Please try again..
        /// </summary>
        public static string ErrorWhileSavingProfile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile was saved successfully..
        /// </summary>
        public static string ProfileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileSavedSuccessfully", resourceCulture);
            }
        }
    }
}
